apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: thanos
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: "prometheus-metrics"
      endpoint: "IPENDPOINT"
      access_key: "KEYHERE"
      secret_key: "KEYHERE"
      insecure: true
